### ISSUE TITLE
Reiter/Tabs

### ISSUE THREAD

**Issue by frankgerhardt** [mitfahrverband/iframe#12]
Entwurf:

![image](https://user-images.githubusercontent.com/550621/166143801-7a951491-765c-4e4e-82fa-99581938b0a5.png)

**Comment by frankgerhardt** [comment]
Ich würde jetzt dafür voten, aber ich sehe nicht wo

**Comment by MartinH-open** [comment]
Ein abgewandelte Version mit Reiterdarstellung ist jetzt aktiv.
