### ISSUE TITLE
Fahrt nur mit Uhrzeit anzeigen

### ISSUE THREAD

**Issue by frankgerhardt** [mitfahrverband/iframe#15]
So wie im Entwurf
![image](https://user-images.githubusercontent.com/550621/166144388-0d9e0efe-c043-4988-89d1-7d9baaaddd2e.png)

**Comment by MartinH-open** [comment]
In der Entwicklung gibt es dazu einen weiteren Parameter und der default kann dann displaydate=off sein.

**Comment by MartinH-open** [comment]
Auf Produktion ist eine neue Version, mit der man über URL Parameter das Anzeigen des Datum an- und ausschalten kann:
Default: `showdate=on' 
oder alternativ `showdate=off'  (später wären andere Angabenwerte denkbar, um das Format festzulegen: d.m.y ...)
Ggfs könnten wir den Default auf off ändern.

**Comment by MartinH-open** [comment]
Der Default für den URL Parameter wurde auf `showdate=off` angepasst und damit erscheint das Datum nur noch auf Extra Wunsch `showdate=on`
Damit ist dies Issue erstmal erledigt.
