### ISSUE TITLE
Anzeige von Datum und Uhrzeit 

### ISSUE THREAD

**Issue by frankgerhardt** [mitfahrverband/iframe#16]
Das betrifft eher RWU wegen #15 

Feedback von Holger 
![image](https://user-images.githubusercontent.com/550621/166144526-5a4c585c-48fd-4935-991c-96e244d65851.png)
Uhrzeit in Zeile 2 suggeriert Ankunftszeit.

**Comment by frankgerhardt** [comment]
> Ich würde Datum und Uhrzeit unterschiedlich färben/Schriftgröße setzen, damit es nicht so aussieht, als bezüge sich Datum auf Start und Zeit auf Ziel

von Holger

**Comment by MartinH-open** [comment]
In der Entwicklungsversion wird Datum unterschiedlich zur Uhrzeit dargestellt. 
So wird eine Verwechselung vermieden.

**Comment by MartinH-open** [comment]
Auf Produktion ist ein fix, der das Datum in einem erweiterten Format dd.mm.yy darstellt: z.b 08.05.22 und damit sollte es erstmal keine Verwechselung mehr geben. 
Ansonsten könnte man die Darstellung (Farbe ) auch noch mal anpassen oder die Anzeigeposition mit der Zeit tauschen.
Gleichzeitig wurde eine Option implementiert, um das Datum nicht zu zeigen `showdate=off'.
