### ISSUE TITLE
Mehr Zeilenabstand

### ISSUE THREAD

**Issue by frankgerhardt** [mitfahrverband/iframe#17]
Vorschlag von Holger

![image](https://user-images.githubusercontent.com/550621/166145260-5299484c-5316-48c2-ab36-b6533f0eff6c.png)

**Comment by MartinH-open** [comment]
UI Design ist in der Entwicklung. Neues Release ist für heute geplant. Der Abstand zwischen Start und Ziel soll aber nicht vergrößert werden. Durch die Perlenschnur ist klar was Start und Ziel ist.

Die Intention der Großschreibung hier ist, zu zeigen, dass dieser Wert gesetzt ist:
Bei der Hinfahrt ist der Zielort fixiert - und kann nicht als Filter genutzt werden (es ist auch nicht mit underline dekoriert).
Bei der Rückfahrt ist der Startort fixiert - und kann nicht als Filter genutzt werden (es ist auch nicht mit underline dekoriert).
Eine andere Möglichkeit einen Ort als fixiert zu markieren, wäre die Fontfarbe zu ändern auf z.B. "Mitfahr-Grün".

**Comment by MartinH-open** [comment]
Aktuell ist die Filterfunktion per default deaktiviert und damit auch unterschiedliche Darstellung für Start- und Ziel-Ort erforderlich. 
Daher wird dies issue erstmal geschlossen.
