### ISSUE TITLE
Mobil-Tauglichkeit

### ISSUE THREAD

**Issue by frankgerhardt** [mitfahrverband/iframe#22]
![image](https://user-images.githubusercontent.com/550621/166253513-b77afebd-590e-4cde-b9b9-fbb1593b1e8f.png)
zu groß

**Comment by MartinH-open** [comment]
Mit iframe Einbindung von  height="1000" width="390" würde die Liste schmaler erscheinen und auch mobil nutzbar sein.
(Sie wäre dann aber auf der webseite auf am Desktop so schmal dargestellt.)
Und die Listendarstellung ist noch nicht für so schmal (390) optimiert.
![image](https://user-images.githubusercontent.com/1383111/166264009-04dab368-0f49-4d83-9445-13b2db922336.png)

**Comment by frankgerhardt** [comment]
1000 ist zu viel. Der iframe sollte klein sein.

**Comment by frankgerhardt** [comment]
Es sieht bei mir aktuell in Prod immer noch so aus wie auf dem ersten Bild.

**Comment by frankgerhardt** [comment]
![image](https://user-images.githubusercontent.com/550621/166518613-054637c3-16e5-47b0-a454-82fd8069962c.png)

In Landscape auch nicht benutzbar

**Comment by frankgerhardt** [comment]
![image](https://user-images.githubusercontent.com/550621/166649626-c926a6e9-bf60-4600-88d0-457da0647a44.png)

Die Tabs sind super :-) Aber der Ort wird jetzt abgekürzt in "Dü.", mit CSS ich weiss. Das Kürzen mit CSS ist gut, aber an dieser Stelle kontraproduktiv. Gefühlt ist mehr als die Hälfte des Platzes Whitespace. 
- der Platz sollte voll genutzt werden, so dass wenig Whitespace entsteht
- wenn gar nicht so viel Platz gebraucht wird, sollte der iframe insgesamt kleiner werden (meine Rede die ganze Zeit ;-) )

**Comment by MartinH-open** [comment]
Jetzt neu nutzt die iframe Einbindung im Beispiel 
`<iframe src="https://ridewithukraine.eu/iframedemo.php" height="840" width="100%"></iframe>`
und damit skaliert die Anzeige des UI im iframe entsprechend mit.

**Comment by frankgerhardt** [comment]
![image](https://user-images.githubusercontent.com/550621/166679497-b2e486a6-a14e-4ec3-964f-4e5e5d899017.png)
100% Breite ist aber nicht die Idee eines iframes. Das ist fullscreen. 
Und dann passt er noch nicht mal in dieses nicht kleine Fenster. 
Mit äußerem Scrollbar und innerem Scrollbar.

**Comment by MartinH-open** [comment]
für den speziellen Anwendungszweck der "Demo in Düsseldorf" kann man es jetzt (ohne width Angabe im iframe) auch mobil nutzen, daher schliesse ich dies Issue. Für einen generellen besseren mobiltauglichen Ansatz können wir dann ein neues Issue bei Bedarf aufmachen.
