### ISSUE TITLE
Tabs ohne grünen Rand

### ISSUE THREAD

**Issue by frankgerhardt** [mitfahrverband/iframe#25]
Vorschlag:

![image](https://user-images.githubusercontent.com/550621/166650899-97b96f6f-6813-4547-95fb-52b9086637e4.png)

Statt aktuell:

![image](https://user-images.githubusercontent.com/550621/166650998-21993399-73e1-4440-ad21-d4904a39a426.png)

**Comment by MartinH-open** [comment]
Ich habe es in meiner Dev Umgebung mal angepasst.
Auf einem 412 px breitem Gerät und dieser  iframe Einbindung sieht es dann so aus:
`<iframe src="https://ridewithukraine.eu/iframedemoMartinH.php" height="840" width="600"></iframe>`


![image](https://user-images.githubusercontent.com/1383111/166666138-c2bea806-bcb8-459c-b728-169b37f909be.png)

**Comment by MartinH-open** [comment]
Die Anpassung ohne grünen Rand ist jetzt aktiv auf Produktion.
