### ISSUE TITLE
iframe ins Wordpress auf MFV Homepage einbetten

### ISSUE THREAD

**Issue by frankgerhardt** [mitfahrverband/iframe#26]
Könnte so aussehen:

![image](https://user-images.githubusercontent.com/550621/166681410-076a3436-d72a-432b-a0d4-14e22d092ee6.png)

**Comment by MartinH-open** [comment]
Habe es direkt in HTML in der rechten Spalte integriert. Funktioniert - auch wenn WP lieber ein Plug-in dafür hätte.
HTML code dafür:
`<iframe src="https://ridewithukraine.eu/iframedemo.php" height="840" width="100%">`

Und so sieht es gerade mobil am Ende der Seite aus:

![image](https://user-images.githubusercontent.com/1383111/166700723-5b61ca34-d8e0-49c8-8a56-d543b86cca17.png)

**Comment by frankgerhardt** [comment]
Super!

![image](https://user-images.githubusercontent.com/550621/166746345-2e95da31-9f97-4b45-b19a-e866ba0cfe2e.png)

Allerdings ;-) noch ein horizontaler Scrollbar im iframe

**Comment by frankgerhardt** [comment]
Und war der grüne Rahmen in den Tab-Headern nicht schon mal weg?

**Comment by MartinH-open** [comment]
Der "grüne Rahmen in den Tab-Headern" ist nur in einer Dev Version schon mal weg - aber nicht auf Produktion.  Siehe #25 

Ein horizontaler Scrollbar im iframe kann auftauchen, wenn ausnahmsweise sehr lange Ortsnamen im Angebot auftauchen und der deep link Knopf nach rechts rauswandert. Das wäre besser ein neues Issue. 
Allerdings erscheint der horizontale Scrollbar auch sonst mal obwohl kein horizontales Scrollen nötig oder möglich. Wenn das stört sollte es auch ein neues Issue werden, denn mit der Einbettung auf der MFV homepage hat es direkt nichts zu tun.
Somit mache ich hier jetzt kein Reopen des Issues.
