### ISSUE TITLE
Verlinkung/Filterung irritierend

### ISSUE THREAD

**Issue by frankgerhardt** [mitfahrverband/iframe#3]
Siehe https://meet.systect.de/playback/presentation/2.3/8ffbd1ef07095711ccdc678099289f22cf6d4ca3-1651402083744

Ich fände es besser den Deeplink zu öffnen, wenn ich auf den Hyperlink (mit Unterstreichung) klicke, im Sinne von [Erwarungskonformität](https://de.wikipedia.org/wiki/Erwartungskonformit%C3%A4t).

**Comment by frankgerhardt** [comment]
Feedback von Holger:

![image](https://user-images.githubusercontent.com/550621/166144475-046d9f49-f311-4c4d-9283-db3b8cf9d8b5.png)

**Comment by MartinH-open** [comment]
1. Die Links zur den Mitfahrportalen sind inzwischen alle klickbar: Ein neues Fenster mit dem aufgerufenen Portal erscheint.
2. "it's a feature - not a bug" 
Bei einer kurzen Angebotsliste braucht man keine Filterfunktion, aber wenn mal Hunderte oder Tausende Angebot in der kurzen Listendarstellung enthalten sind, kann ein Filtern nach ähnlichen Abfahrts/Ziel-Orten schon sehr hilfreich werden.
=> Das Filter-feature wird gerade noch überarbeitet.

**Comment by MartinH-open** [comment]
Da im Moment keine weiteren Filter- und Anzeige-funktionen nötig sind, bei der kleinen Datenmenge, ist die Filterfunktion standardmäßig deaktiviert und kann über einen URL Parameter wieder aktiviert werden.

**Comment by frankgerhardt** [comment]
Dann könnte doch der ganze Eintrag klickbar sein, statt nur des relativ kleinen Buttons?
![image](https://user-images.githubusercontent.com/550621/166679188-1ab2896b-95ef-4b93-a727-0a70addaaee0.png)
Hat mich erst irritiert.
