### ISSUE TITLE
Rahmen um Logos verrutscht

### ISSUE THREAD

**Issue by frankgerhardt** [mitfahrverband/iframe#4]
![image](https://user-images.githubusercontent.com/550621/166142853-5c723ac3-151d-4a30-abfa-6dfa36b12b3d.png)

**Comment by frankgerhardt** [comment]
Am Besten fände ich es, wenn das Logo keinen Rahmen hätte und der ganze weiße Bereich als Link zum Deeplink funktionieren würde

**Comment by MartinH-open** [comment]
Der Rahmen des Buttons passt sich dynamisch an die Länge der Ortsbeschreibung an. Wenn sehr lange Ortsbeschreibungen auftauchen, wird aktuell der Button etwas kleiner. Layout des Button wird gerade überarbeitet.

**Comment by MartinH-open** [comment]
Das Layout dieses Button wurde verändert.
Abstände, Icongröße und Ecken verkleinert:
![image](https://user-images.githubusercontent.com/1383111/166162852-155cdab5-0fd1-4f84-83df-3dd2957a3f52.png)
Buttongröße ändert sich nur noch bei sehr langen Ortsbezeichnungen um Platz zu schaffen.
Ausserhalb des Buttons kann die Fläche berührt werden, das Datenfenster zu scrollen.
Wenn die gesamte Fläche den Deeplink aktiviert, könnte dies leicht aus Versehen passieren. So lernt der Nutzer den Button für die Buchung und Details zu nutzen. Vielleicht gibt es später noch andere Funktion für ein Fahrtangebot, wie Details im Pop-up anzeigen oder weitere Filter (Uhrzeit, ...)

**Comment by MartinH-open** [comment]
Die Formatierung um den Rahmen wurde verbessert und insgesamt einheitlicher und kleiner. 
Wenn Nutzer gelernt habe das Icon zu nutzen, kann der Rahmen auch entfallen.
Ggfs könnte auch der Gesamtrahmen um das jeweilige Angebot entfallen, weil auch so klar sein sollte, was ein Angebot darstellt.
