### ISSUE TITLE
Parameter beschreiben

### ISSUE THREAD

**Issue by frankgerhardt** [mitfahrverband/iframe#5]
> An der URL sieht man schon wohin es geht: https://ridewithukraine.eu/iframedemo.php?go=to&location=D%C3%BCsseldorf 
(aktueller Stand zur Diskussion der Logo Darstellungen)

Ich sehe die Parameter zum ersten Mal. Was sind die und was machen die?

**Comment by MartinH-open** [comment]
Die Parameter sind noch vorläufig und iframe funktioniert im Aufruf auch ohne Parameter mit Default Werten.
bisherige Parameter:
- go :  zur Umschaltung zwischen Hinfahrt zur Veranstaltung und Rückfahrt nach der Veranstaltung
  Werte: to , from
  - to : Hinfahrt
  - from : Rückfahrt
- location : noch ungenutzt
- .. weitere Parameter sind in Planung

**Comment by MartinH-open** [comment]
Der Zustand (die Auswahl bestimmter Funktionen wie Hinfahrt oder Rückfahrt) wird aktuell über URL Parameter an den nächsten Aufruf übertragen. Der Aufruf nur mit Defaultwerten ohne diese anzugeben bzw. den rein veranstaltungsrelevanten Daten erfolgt über den Start Knopf [M] Logo.
Inzwischen werden nur die URL Parameter für den nächsten Aufruf übertragen, wenn sie nicht dem default Wert entsprechen. So wird die URL kürzer und man erkennt sofort die Abweichungen zum Standardverhalten.

**Comment by MartinH-open** [comment]
Aktive Parameter sind jetzt im Readme beschrieben. 
Es werden wahrscheinlich noch einige Parameter mehr werden, wenn wir die Funktionen ausbauen, die dann auch dokumentiert werden sollten.
